security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        wordpress_provider:
            id: App\Security\WordpressUserProvider # Utilisez le service que vous venez de créer
        users_in_memory:
            memory:
                users:
                    test_user:
                        password: null
                        roles: 'ROLE_USER'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # PARE-FEU N°1 : EXCEPTION POUR LE LOGIN (PUBLIC)
        # Il est lu en premier car il est plus spécifique.
        login:
            pattern:  ^/api/login_test
            stateless: true
            security: false # <-- ACCÈS PUBLIC AUTORISÉ

        # PARE-FEU N°2 : SÉCURITÉ POUR LE RESTE DE L'API (PRIVÉ)
        api:
            pattern:   ^/api
            stateless: true
            provider: wordpress_provider
            jwt: ~

    access_control:
        # On ne protège que les routes /api, mais PAS la route de login
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/login_test, roles: PUBLIC_ACCESS }

# ... when@test reste inchangé ...
when@test:
    security:
        # ...